Algoritmo "Exercicio8"
// Disciplina  : [Lógica de Programação com Visual G]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Algoritmo que recebe o valor do raio de um círculo para
//calcular o comprimento de sua borda através da multiplicação de duas vezes
//a constante pi pelo raio e exibe o resultado final na tela.
// Autor(a)    : Mary Lacerda da Cunha
// Data atual  : 04/04/2026
Var
   // Seção de Declarações das variáveis
   raio, comprimentoC: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o valor do raio: ")
   leia(raio)

   comprimentoC<- 2 * 3.14 * raio

   escreval("O comprimento da circunferência é: ", comprimentoC)

Fimalgoritmo
