Algoritmo "Exercicio7"
// Disciplina  : [Lógica de Programação com Visual G]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Algoritmo que solicita o raio de um círculo para calcular
//sua área total multiplicando o valor da constante pi pelo quadrado do raio
//e exibe o resultado final no console.
// Autor(a)    : Mary Lacerda da Cunha
// Data atual  : 04/04/2026
Var
   // Seção de Declarações das variáveis
   raio, area: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o valor do raio do círculo: ")
   leia(raio)

   area<- 3.14 * (raio * raio)

   escreval("A área do círculo é: ", area)

Fimalgoritmo
