Algoritmo "Exercicio3"
// Disciplina  : [Lógica de Programação com Visual G]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Algoritmo que solicita a medida do lado de um quadrado para
//calcular o valor total do seu perímetro através da multiplicação por quatro
//e exibir o resultado da soma de todos os lados na tela.
// Autor(a)    : Mary Lacerda da Cunha
// Data atual  : 04/04/2026
Var
   // Seção de Declarações das variáveis
   perimetro, lado: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite a medida do lado do quadrado: ")
   leia(lado)

   perimetro<- lado * 4

   escreval("O perímetro do quadrado é: ", perimetro)

Fimalgoritmo
