Algoritmo "Exercicio2"
// Disciplina  : [Lógica de Programação com Visual G]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Algoritmo que recebe a medida do lado de um quadrado para
//calcular sua área total através da multiplicação do valor por ele mesmo
//e exibir o resultado final para o usuário.
// Autor(a)    : Mary Lacerda da Cunha
// Data atual  : 04/04/2026
Var
   // Seção de Declarações das variáveis
   area, lado: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite a medida do lado do quadrado: ")
   leia(lado)

   area<- lado * lado

   escreval("A área do quadrado é: ", area)

Fimalgoritmo
