Algoritmo "Exercicio5"
// Disciplina  : [Lógica de Programação com Visual G]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Solicita um número e exibe o seu antecessor
// Autor(a)    : Mary Lacerda da Cunha
// Data atual  : 27/03/2026
Var
   // Seção de Declarações das variáveis
   numero: inteiro
   resultado: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva ("Digite um número inteiro :")
   leia (numero)
   resultado<- numero - 1
   escreval ("O antecesser do numero ", numero, " é :", resultado)

Fimalgoritmo