Algoritmo "Exercicio22"
// Disciplina  : [Lógica de Programação com Visual G]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Solicita um valor ao usuário e verifica se ele é maior que 10,
// exibindo uma mensagem de confirmação ou de negação baseada no resultado.
// Autor(a)    : Mary Lacerda da Cunha
// Data atual  : 28/03/2026
Var
   // Seção de Declarações das variáveis
   numero: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva ("Digite um número :")
   leia (numero)

   se numero > 10 entao
      escreval("Esse número é maior que 10")
   senao
      escreval ("Esse número é menor que 10")
   fimse

Fimalgoritmo
