Algoritmo "Exercicio8"
// Disciplina  : [Lógica de Programação com Visual G]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Solicita um valor em metros e exibe o resultado em centímetros
// Autor(a)    : Mary Lacerda da Cunha
// Data atual  : 27/03/2026
Var
   // Seção de Declarações das variáveis
   medida: real
   metros: inteiro
   resultado: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   metros<- 100
   escreva ("Digite um valor em metros :")
   leia (medida)
   resultado<- medida * metros
   escreval ("Seu valor convertido em centímetro é de :", resultado)

Fimalgoritmo
