Algoritmo "Exercicio5.6.1.1.A"
// Disciplina  : [Lógica de Programação com Visual G]
// Professor   : Jailson Costa Dos Santos
// Descrição   : O algoritmo utiliza um laço de repetição com limites fixos
//para percorrer todos os números inteiros entre 15 e 200. Para cada valor
//dentro desse intervalo, o programa calcula o seu quadrado multiplicando o
//número por ele mesmo e exibe o resultado imediatamente na tela.
// Autor(a)    : Mary Lacerda da Cunha
// Data atual  : 22/04/2026
Var
   // Seção de Declarações das variáveis
   contadora, quadrado: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para contadora de 15 ate 200 faca
      quadrado <- contadora * contadora
      escreval("O quadrado de ", contadora, " é: ", quadrado)
   fimpara

Fimalgoritmo
