Algoritmo "Exercicio4.K"
// Disciplina  : [Lógica de Programação com Visual G]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Este algoritmo solicita um número inteiro e só exibe o número
//na tela se ele não for maior que três.
// Autor(a)    : Mary Lacerda da Cunha
// Data atual  : 17/04/2026
Var
   // Seção de Declarações das variáveis
   valor: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite um valor inteiro: ")
   leia(valor)

   se (valor < 3) entao
      escreval("O valor digitado foi: ", valor)
   fimse

Fimalgoritmo
